### ISSUE TITLE
Chimes at 6 after the hour

### ISSUE THREAD

**Issue by jonsafari** [raatmarien/chibe#3]
I'm not sure why Chibe is chiming at 6 minutes after the hour (eg. 9:06, 10:06, etc), instead of on the hour.  My phone's time is correct.  How can I change the time of the hour?  Thanks!

**Comment by raatmarien** [comment]
Thanks for letting me know about this issue!

This is a bug, Chibe should chime exactly on the hour (and it does on the devices I tested it on). This may be related to your version of Android's implementation of the AlarmManager, so it would be helpful if you could give me some information about your device.

Could you tell me what device you are using, what version of android you are using and if you have any battery saving features enabled? Could you also try if rebooting your device changes the times at which Chibe chimes? Thanks in advance.

Lastly I would like to know how consistently Chibe chimes at 6 past the hour. Does it always chime at exactly 6 past, or does it vary?

If anyone else is experiencing this issue, feel free to leave a comment.

**Comment by jonsafari** [comment]
No battery-saving features are enabled.  In the past few days, I've noticed that the times it chimes at are quite inconsistent:  often at 6 minutes after, but sometimes at 1 or 3 after, and once about 30 seconds before the hour.
I've rebooted the phone, and I'm testing it now for every minute.  The first minute was on time (and the phone was awake).  Then I hit the power button to get it to sleep.  It chimed about 17 seconds late, and since then it hasn't chimed at all (5 minutes later).   When I hit the power button to get it to wake up, it immediately chimed.
I suspect it's an issue with power saving, but again, no power-saving features have been enabled as far as I know (viz.  under Settings->Battery->Battery Saver).
Thanks!

**Comment by pvagner** [comment]
Hello,
On Cyanogenmod cm-13 and CM-14 / Lineage OS this app works fine for me. It vibrates a few seconds after the scheduled time e.g. at 17:00:02 or at 17:15:35 or similar.
When used on branded Android version such as Android 6 on LG G3 or Android 6 on Samsung Galaxy S VII it vibrates at random times such as at 17.02:35 17:03:50 17:7:15 and similar. On LG G3 it's much worse than on Samsung galaxy S VII I have noticed it vibrating at very very random times such as 13:07, 13:23, 17:48, 17:38 and similar.
Please note I do have configured it to vibrate each 15 minutes. On LG G3 I have excluded it from battery optimizations and it did not seem to help. On S VII have to try it.
Can I grab a log or do some more trouble shooting to help address this?

**Comment by raatmarien** [comment]
It seems the trouble is that (especially custom branded versions of Android) heavily optimize alarms to save battery life, so they don't always let Chibe react to the alarm at the right time. I'm not sure it is possible to completely solve this, but [v1.2.0](https://github.com/raatmarien/chibe/releases), which I just released and should be on F-Droid in a few days, uses a new API call on the latest Android versions which should improve the punctuality of Chibe. Hopefully this will solve the problem for you, please let me know if it doesn't.

**Comment by pvagner** [comment]
I know you have done the most you can do here but on my Galaxy S VII it is still not working as intended. When the screen is on or when the device is connected to charger it vibrates exactly as scheduled. This has improved dramatically in the 1.2.0 version.
However when the screen is off and device is not connected to charger it vibrates consistently about 2 or three minutes after the scheduled time for me.

**Comment by raatmarien** [comment]
Hmm, that's unfortunate. I've added another flag in v1.2.1, which should be on F-Droid in a few days. Hopefully that flags fixes this behaviour on your device, otherwise I'm not sure there is anything more I can do.

**Comment by pvagner** [comment]
Unfortunatelly my S VII still chibes 3 or 4 minutes after the scheduled timer.
Most likelly it helped for LG G3 but it needs more testing on that. I'll report later as I find it.
